name: simple_sparse_list
description: A simple and efficient implementation of an unmodifiable sparse list based on the binary search algorithm.
version: 0.1.0
homepage: https://github.com/mezoni/simple_sparse_list
environment:
  sdk: '>=3.0.0 <4.0.0'
dev_dependencies:
  lints: ^5.0.1
  test: ^1.25.14
